
# global style
style = ["config/global/style.css", "config/portal/item-flex.css"]
# mobie support
head = ["config/global/head.html"]

[main]

# heading
[[main.block]]
style = "h1"
text = "ToastXC"

# topnav
[[main.block]]
from_str = "config/global/topnav.md"
style = "html"


[[main.block]]
style = "h3"
text = "Internal"


# Main site info
[[main.block]]
from_str = "config/portal/in-portal.html"
style = "md"


[[main.block]]
style = "h3"
text = "External"

[[main.block]]
from_str = "config/portal/ex-portal.html"
style = "md"

# breakline
[[main.block]]
style = "br"

# footer
[[main.block]]
from_str = "config/global/footer.html"
style = "html"
