
style = ["config/global/style.css"]
head = ["config/global/head.html"]
# main holds the body of the document in main there are blocks which have properties
[main]


[[main.block]]
style = "h1"
text = "ToastXC"


# topnav
[[main.block]]
from_str = "config/global/topnav.md"
style = "html"


# Minecraft server
[[main.block]]
from_str = "config/minecraft/server.md"
style = "md"


# Fox client
[[main.block]]
from_str = "config/minecraft/fox.md"
style = "md"

#  copyright
[[main.block]]
from_str = "config/global/footer.html"
style = "html"