
style = "config/global/style.css"

# main holds the body of the document in main there are blocks which have properties
[main]


[[main.block]]
style = "h1"
text = "404"

[[main.block]]
from_str = "config/global/topnav.md"
style = "html"


[[main.block]]
style = "h2"
text = "We could not find this document"
