
style = ["config/global/style.css"]
head = ["config/global/head.html"]

[main]

# title
[[main.block]]
style = "h1"
text = "ToastXC"

# topnav
[[main.block]]
from_str = "config/global/topnav.md"
style = "html"


# Main site info
[[main.block]]
from_str = "config/policies/policies.md"
style = "md"

# copyright
[[main.block]]
from_str = "config/global/footer.html"
style = "html"