
style = ["config/global/style.css"]
head = ["config/global/head.html"]
# main holds the body of the document in main there are blocks which have properties
[main]


[[main.block]]
style = "h1"
text = "ToastXC"

[[main.block]]
from_str = "config/global/topnav.md"
style = "html"


# Main site info
[[main.block]]
from_str = "config/index/aboutme.md"
style = "md"

[[main.block]]
style = "br"

[[main.block]]
style = "br"


[[main.block]]
from_str = "config/global/footer.html"
style = "html"
