
style = ["config/global/style.css"]
head = ["config/global/head.html"]
[main]


[[main.block]]
style = "h1"
text = "StatSite"


# Main site info
[[main.block]]
from_str = "config/statsite/main.md"
style = "md"

[[main.block]]
style = "br"

[[main.block]]
style = "br"


[[main.block]]
from_str = "config/global/footer.html"
style = "html"
